photogur/config/routes.rb
Photogur::Application.routes.draw do
  resources :pictures

  root :to => "pictures#index"

end

photogur/app/models/picture.rb
class Picture < ActiveRecord::Base

scope :newest_first, -> { order("created_at DESC")}
scope :most_recent_five, -> { newest_first.limit(5)}
scope :created_before, -> {where("created_at < ?", 1.month.ago)}





end
 

photogur/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

photogur/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

	def index

	@newest_first = Picture.newest_first
  @created_before = Picture.created_before
    
  end

  def show
    @pictures = @picture = Picture.find(params[:id])

  end

  def new
    @picture = Picture.new
  end

  def create
      @picture = Picture.new(picture_params)

      if @picture.save
        redirect_to pictures_url

      else
        render :new

      end
          
  end
  


  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])


    if @picture.update_attributes(picture_params)
      redirect_to "/pictures/#{@picture.id}"
    else
      render :edit
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_url
  end

    def self.artist(artist)
    Picture.where("artist = ?", artist)
   end

  def self.title(title)
    Picture.where("title = ?", title)
  end

  def self.url(url)
    Picture.where("url = ?", url)
  end
  
  private
  def picture_params
    params.require(:picture).permit(:artist, :title, :url)
  end 
end 

photogur/app/helpers/application_helper.rb
module ApplicationHelper
end

photogur/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

photogur/app/views/pictures/edit.html.erb
<h1>[photogur]</h1>
<h2>edit</h2>

<p>
	<%= link_to "back to [photos]", @picture %>
</p>

<%= form_for @picture do |f| %>
	<p>
		<%= f.label "artist" %>
		<br>
		<%= f.text_field "artist" %>
	</p>

	<p>
		<%= f.label "title" %> 
		<br>
		<%= f.text_field "title" %>
	</p>

	<p>
		<%= f.label "url" %>
		<br>
		<%= f.text_field "url" %>
	</p>

	<p>
		<%= submit_tag "Save" %>
	</p>
<% end %>
<footer>
<p>[photogur], created by morris web dev inc., 2013</p>
</footer>

photogur/app/views/pictures/index.html.erb
<h1>[photogur]</h1>

<%= link_to "upload", "/pictures/new" %>


<ul>
<% @newest_first.each do |picture| %>
		<li><%= picture.title %></li>
		<%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
	<% end %>
</ul>

<h2>older [photos] - one month+</h2>
<ul>
<% @created_before.each do |picture| %>
		<li><%= picture.title %></li>
		<%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
	<% end %>
</ul>

<%= Picture.created_before.count %>

<footer>
<p>[photogur], created by morris web dev inc., 2013</p>
</footer>

photogur/app/views/pictures/new.html.erb
<h1>[photogur]</h1>
<h2>upload</h2>
<%= link_to "back to [photos]", pictures_url %>


<%= form_for @picture do |f| %>

<p>

	<%= f.label "artist" %> 
	<br>
	<%= f.text_field "artist", :class => 'textfield'  %>
</p>

<p>
	<%= f.label "title" %>
	<br>
	<%= f.text_field "title", :class => 'textfield' %>
</p>

<p>
	<%= f.label "url" %>
	<br>
	<%= f.text_field "url", :class => 'textfield'  %>
</p>

<p>
	<%= submit_tag "save" %>
</p>

<% end %>
<footer>
<p>[photogur], created by morris web dev inc., 2013</p>
</footer>

photogur/app/views/pictures/picture0.html.erb
<p><%= @picture[:title] %>, <%= @picture[:artist] %> </p>

<img src="<%= @picture[:url] %>">

photogur/app/views/pictures/picture1.html.erb
<p><%= @picture[:title] %>, <%= @picture[:artist] %> </p>

<img src="<%= @picture[:url] %>">

photogur/app/views/pictures/picture2.html.erb
<p> <%= @picture[:title] %>, <%= @picture[:artist] %> </p>

<img src="<%= @picture[:url] %>">

photogur/app/views/pictures/show.html.erb
<h1>[photogur]</h1>
<%= link_to "back to [photos]", pictures_url %> | <%= link_to "edit", edit_picture_path(@picture) %> | <%= link_to "delete", @picture, :confirm => "are you sure you want to delete this [photo]?", :method => :delete %>

<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>

<%= image_tag @picture.url %>
<footer>
<p>[photogur], created by morris web dev inc., 2013</p>
</footer>